train_config:
  dset_dir: "${HOME}/final_project/data"
  seed: 2021
  dset_size: 30000
  num_splits: 5
  batch_size: 128
  num_workers: 8
  pipeline_params:
    # lr: 0.0002 # 2e-4
    lr: 0.001 # 1e-3
    num_epochs: 15
    model_params:
      c_in: 3
      c_out: 1
      seq_len: 4096
      num_features: 10000 # number of random kernels
    scheduler_params:
      T_0: 5
      T_mult: 1
      eta_min: 0.000001 # 1e-6 min LR
    logdir: "${PFSDIR}/log"
